% Auto-generated by cameraCalibrator app on 18-Dec-2017
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\bh\users_EV\sandpit\bh_car_models\Task_virtual_camera\Calibration\bh_checkbrd_m5.JPG',...
    'C:\bh\users_EV\sandpit\bh_car_models\Task_virtual_camera\Calibration\bh_checkbrd_m10.JPG',...
    'C:\bh\users_EV\sandpit\bh_car_models\Task_virtual_camera\Calibration\bh_checkbrd_m15.JPG',...
    'C:\bh\users_EV\sandpit\bh_car_models\Task_virtual_camera\Calibration\bh_checkbrd_m20.JPG',...
    'C:\bh\users_EV\sandpit\bh_car_models\Task_virtual_camera\Calibration\bh_checkbrd_p0.JPG',...
    'C:\bh\users_EV\sandpit\bh_car_models\Task_virtual_camera\Calibration\bh_checkbrd_p5.JPG',...
    'C:\bh\users_EV\sandpit\bh_car_models\Task_virtual_camera\Calibration\bh_checkbrd_p10.JPG',...
    'C:\bh\users_EV\sandpit\bh_car_models\Task_virtual_camera\Calibration\bh_checkbrd_p15.JPG',...
    'C:\bh\users_EV\sandpit\bh_car_models\Task_virtual_camera\Calibration\bh_checkbrd_p20.JPG',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 70;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
